### ISSUE TITLE
The property 'ssousername' cannot be found on this object.

### ISSUE THREAD

**Issue by knxroot** [knxroot/chocolatey-oracle-sql-developer#1]
NeonVanadiumIndium • 4 days ago • edited
Hi,

executing:

choco install -y oracle-sql-developer --params='"/Username:{username} /Password:{password}"' --verbose

getting error:

VERBOSE: Importing alias 'Start-ChocolateyProcess'.
Redirecting to Oracle Login...
VERBOSE: GET https://download.oracle.com... with 0-byte payload
VERBOSE: received 3960-byte response of content type text/html;charset=UTF-8
Logging in...
ERROR: The property 'ssousername' cannot be found on this object. Verify that the property exists and can be set.
The install of oracle-sql-developer was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\oracle-sql-developer\tools\chocolateyinstall.ps1'.
See log for details.

looks like oracle have changed something (again🙄)

**Comment by knxroot** [comment]
Fixed at knxroot/chocolatey-oracle-sql-developer@03a6ee8

**Comment by H4DDSTER** [comment]
Has this broken again??  I'm seeing this error

ERROR: The property 'ssousername' cannot be found on this object. Verify that the property exists and can be set.
The install of oracle-sql-developer was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\oracle-sql-developer\tools\chocolateyinstall.ps1'.
