### ISSUE TITLE
error al instalar utilizando parametros recomendados

### ISSUE THREAD

**Issue by Potencial** [knxroot/chocolatey-oracle-sql-developer#2]
Chocolatey v0.10.15
Windows 10 Pro 19042.928

choco install -y oracle-sql-developer --params="'/Username:username /Password:password'"

Chocolatey v0.10.15
Installing the following packages:
oracle-sql-developer
By installing you accept licenses for the packages.
Progress: Downloading oracle-sql-developer 20.4.1.20210328... 100%

jdk8 v8.0.211 [Approved]
jdk8 package files install completed. Performing other installation steps.
Downloading JDK from https://javadl.oracle.com/webapps/download/GetFile/1.8.0_211-b12/478a62b7d4e34b78b671c754eaaf38ab/windows-i586/jdk-8u211-windows-x64.exe
Installing jdk8...
jdk8 has been installed.
PATH environment variable does not have C:\Program Files\Java\jdk1.8.0_211\bin in it. Adding...
  jdk8 may be able to be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of jdk8 was successful.
  Software installed to 'C:\Program Files\Java\jdk1.8.0_211\'

oracle-sql-developer v20.4.1.20210328 [Approved]
oracle-sql-developer package files install completed. Performing other installation steps.
Redirecting to Oracle Login...
Logging in...
<html>
<script language="javascript" type="text/javascript">
function submitForm()
{
var hash = location.hash;
if (hash) {
if(hash.indexOf("#") == -1){
hash="#"+hash
}
document.myForm.action = document.myForm.action+hash;
}
document.myForm.submit();
}
</script><head><base target="_self"></head><body onLoad="submitForm()"><noscript><p>JavaScript is required. Enable JavaScript to use OAM Server.</p></noscript><form action="https://login.oracle.com/mysso/signon.jsp" method="post" name="myForm"><input type="hidden" name="bmctx" value="9E1E7DBD1B88FA0EDC1F7E37E421616DF7C310512F22CB750228F25FCC742C2E"><input type="hidden" name="contextType" value="external"><input type="hidden" name="username" value="string"><input type="hidden" name="contextValue" value="%2Foam"><input type="hidden" name="challenge_url" value="https%3A%2F%2Flogin.oracle.com%2Fmysso%2Fsignon.jsp"><input type="hidden" name="password" value="secure_string"><input type="hidden" name="request_id" value="-1541276180264924534"><input type="hidden" name="authn_try_count" value="1"><input type="hidden" name="OAM_REQ" value="VERSION_4~9r3Ubj%2bWELOOUNPSYhYM2xRrz%2bZBXB1iQsEQEyf2Dd1WcpPFtqdPwen06cGDYXGcaEmttyX3bEy1edstEZ%2b1TazBdxzipegn6kBVtQ%2bbyajNJFefzHrM2%2fiyL2lTTuT%2fYQ7SEJEs7pcipBN3KLZ7PidEI1gEwzwWMXWpTpHWrPcHEGXKGEdHwtVK0dXTApxIPpDa6si2F3tirMli8eTu%2fUsf9X1SENIk7DrFz4hK3h2jFemsYKEh4%2fC%2fRDeXODnb8dSlowM%2bQ5eQqwCuqxgHg5WWOGt0iFuPewBoicVqBl1ccbNQ%2fZ2qwrC9qUwrvhlz%2bz11Nc7oI8OT03lvBbU0AKtfmMRURffZSQHVAuMUmpmaUSeZHSc7vLgskNITYDO65CAy5znWXDkBJYLqLXzNdSArcPbhgNBDWsFhLuLwCwMtHfTDPUKt4%2f%2bTNIorsxw8pVTDiCz5MhHQMa9lIfa%2fLTyV0imwPaO1H4WzvU89Gml5luq4nThChQyDX3rnmW2k%2fiUN3cRI7tPw5cJLh8ZTeo1QoCgk%2bXlUa4drAfmIgSf8L%2beYlhdORIwdYFvmSRbZwc%2fTdgx7riKchen4newVpGUmhWxy0FTXkTnzJytPJbuP091VwBcCwhLQFkV8p4EvNIwuRtTVWzT5Pw8CX%2bKpeC0zxKd%2bc5optJEsrT9VdQ%2bjIAl%2fd6%2bhzFRAQY44ESnrF%2blJ%2bY%2fXFpQpzUWXwl8%2bZj0eKk0gaOrqk%2fsXaBykRPDWD%2bpEO3J4I41dIeY7tqwPtkx4dSy19WV3yI5E9%2f56XufVAnzic3YuDZ9SkdcXzWNZBUfPcpY%2fy7ZysX3NNoMpp%2bEP%2bZGutGpDAODS4Nt4Gq%2bAGkniLlsczD5%2f4IEUESsA3NxxPillLZpvJFm%2bFtWPW17aHj6byoORzsi8flNAkf6FWBsq2%2fc6IWCig4dTFk%2bunvJIRlU5jThfDwSICTTOOxkQXHSlyEKjfIys9ayxLRcLQDMjFdQj6iY7fd689hTABjyva3zGBCBIFjqHhIwWvho6HY%2b8imqTRnNUDpESpzMMy4ECZkB95zuj%2bxY7JRcYlDvOlsfNdoMZQR1Rvrw3%2fsSJQIvSwKDnWd5CqzoWlNM5d5VZHr1RuvN606rTgpA7A296Is67c70h3NPsbZ9UMfCLCv6XSSho2h8ptjml0%2fdYetIZmvvnCpK84tAgkP%2fHOyCfiXBgwH%2bymdBPaYz7xfFUfM0ZSubpSL1Jr%2b4vRrLz6kJ29SciQ2kjVuyvO5RbgyRI102ZtOvTva%2ftrtwfCaPU6TjZBWkmsfa5NA5bmXI5TejqWp1WC35LleMZaTKKM7VTwALLxiPmgPvQwmysCVX4rHioOsAKq7PYeuYlV4nPHRD4XIcz6FtcrHwaR9ro5BJp%2bjeQq5LbljCnbNolxMqyT0nJRvlVmj0gafOb0576LeqBgRfA%2f%2fhfh5xn4OG24bbxdTGJQnkMv%2b8TG7HFUhFfaGQgegSknNJtKXYvq19s9Xc0WOt8Z8mXgXDaakPvRkZ6%2fBsCWm0KU8zkZAB3OlV6bAMTLeS7e5EagbjklAf%2bsdIO6wxGEM4E%2fLJkSpR8Q4DvIU66W7fIjMI8mrLW%2fVkbtXSIvvKbvzaOdezPCtgH4nh7UcuhwEps1SFvC8wCUS7cR01DHEat6Z4oqjdBbL5%2f8Bl9R7i6eVXlO4leGs5G4DOUo8eg5cwz5t0g5y%2fSJwDcDLevEzvnpNxTmIriji9YoCdckJdtFSzqWHa%2fBrFMkQ6aPjV7SOKkV3IG9myFPHirpCchnGK93p5VaKRBKPgUvscRtogNFNHa2%2f9c1Y11142KellXFGzrIpZY7HRNZloA%2fE0b15Xh7uhh%2b6tHyOc8my4nMXrl%2bqF%2bqmXTWxAjR3zYmLcOv5nlyP54hbPRbb97atS0HGRiOUE31oI8ujqfsg68sBykEtG%2bMnWe77oMCgvmDS1m%2fLsFRPJWb63rjD7f472imym4%2b5Dp4SEqDDx1uY0yHEKIIX21ZcNSkTmKUErbHaLuG4%2bTQ1LaeLmP2w94kABJCiyedv1RRiRdvIKEN63hqmBgO3ebn%2fIcfHQOKFPL18v2iwMn9U1SAdGwpTROLjBDyUxPR1biqR%2fatCwnufZPfQAevY%2br7JD6fnmOBACyCzI4C5zFu9FYXFg5eKvxI%2blNWR9HfwfBqam0Tc2EOxMydHaX5IGwLORpmGOkiahpte%2bpHtcg%2f3XE7lDXEnYkMyv4LK7Bsn204kdMV3chu5ulnbbPDL8L%2fJ2%2bDuCt1t%2bzQJUgfghFB5pSkCdE3g2QtKAoNMsx5NVhqhoIEjAOR6Y3N9OYtgfi1LbsMD30cxzn4z2Ud81GdH90KQfAenat9qQtEcqYCx2EAUoMVGqcHWiigx%2bKoHaCZ%2b%2fn81%2frzzADUylZQCl1Vk9%2b8JgzbRgFqGu3LXNtv9VQ4W6mQ8QLPhW7vrQaHig%2f%2bRiZGGcB5Yrz5vuonaaYA09Pus8%3d"><input type="hidden" name="p_error_code" value="OAM-7"><input type="hidden" name="p_error_codes_list" value="OAM-7"><input type="hidden" name="locale" value="en"><input type="hidden" name="resource_url" value="https%253A%252F%252Fedelivery.oracle.com%252Fakam%252Fotn%252Fjava%252Fsqldeveloper%252Fsqldeveloper-20.4.1.407.0006-no-jre.zip"></form></body></html>
Oracle login successful
ERROR: This package does not support 64 bit architecture.
The install of oracle-sql-developer was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\oracle-sql-developer\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 1/2 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - oracle-sql-developer (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\oracle-sql-developer\tools\chocolateyinstall.ps1'.
 See log for details.

**Comment by knxroot** [comment]
La instalación requiere que ingreses el usuario y una contraseña de tu cuenta en oracle. Por ejemplo si tu usuario es test@gmail.com y tu password es ThePassword, el comando para instalar sería:

choco install -y oracle-sql-developer --params="'/Username:test@gmail.com /Password:ThePassword'"

Esto es requerido debido a que por políticas de oracle la descarga requiere login.
